// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpE2R8eLA_FNIL2V4sLCvLo7n0rDDdqAo',
    appId: '1:822679231912:web:a0a6cd2f4c0f1185b3519d',
    messagingSenderId: '822679231912',
    projectId: 'chat-app-cb713',
    authDomain: 'chat-app-cb713.firebaseapp.com',
    databaseURL: 'https://chat-app-cb713-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-cb713.appspot.com',
    measurementId: 'G-7ZLGR4K0YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTT2ujKjIZLkS8emiBJMpSfe1c8AuwtYI',
    appId: '1:822679231912:android:fe4a9983a8467901b3519d',
    messagingSenderId: '822679231912',
    projectId: 'chat-app-cb713',
    databaseURL: 'https://chat-app-cb713-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-cb713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_adCvWWiErK5h-2XTIXPslYtIa0CM8A',
    appId: '1:822679231912:ios:cf6bff24ddd5e2d9b3519d',
    messagingSenderId: '822679231912',
    projectId: 'chat-app-cb713',
    databaseURL: 'https://chat-app-cb713-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-cb713.appspot.com',
    iosClientId: '822679231912-07cl4k7nnd1vooorlm9nc6sakgelm2e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.guzogoClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_adCvWWiErK5h-2XTIXPslYtIa0CM8A',
    appId: '1:822679231912:ios:4e38f5f7b6909ea1b3519d',
    messagingSenderId: '822679231912',
    projectId: 'chat-app-cb713',
    databaseURL: 'https://chat-app-cb713-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-cb713.appspot.com',
    iosClientId: '822679231912-du1vl4cilqkg9915ocpv9cfrc9c0uaqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.guzogoClone.RunnerTests',
  );
}
